### ISSUE TITLE
Support for merging mmdb or csv files？

### ISSUE THREAD

**Issue by photkey** [ipinfo/mmdbctl#19]
Is it supported to merge two mmdb or csv files that record different information?

For example, one is an mmdb or csv file that records country information, and the other is a file that records ASN. Is it possible to merge these two files into one that contains both ASN and country information, just like the three free databases you provide officially?

If it is possible to implement, can you give me an example of a specific command? If it is not possible to implement temporarily, is it possible to implement it in the future?

**Comment by UmanShahzad** [comment]
@photkey that's tough to do, not because of the different data per-se, but because the data is indexed by start/end IP ranges and you'd have to solve the problem of joining, aggregating, flattening, etc. the two different sets of start/end IP ranges.

This is something we do when producing these MMDB/CSV files in data pipelines, and that's already a very tough and costly process (can take hours to produce even small files).
